### ISSUE TITLE
Translatie de petitie index. 

### ISSUE THREAD

**Issue by Tjoosten** [CPSB/nato.activisme.be#16]
We hebben de translaties ontvangen van Peter Terryn. En deze zouden geimplementeerd moeten worden in het platform. 

- **INTRO:** https://drive.google.com/open?id=0B59ywPdTlEekN042eHlmTV9fRXM
- **ONTBINDING FR:** https://drive.google.com/open?id=0B59ywPdTlEekNXU0NE5vNEhaeTg
- **ONTBINDING ENG:** https://drive.google.com/open?id=0B59ywPdTlEekd1BSakJLc0VFdjQ

## TODO log:

- [x] Verweving van de intro. 
- [x] Translatie intro NL
- [x] Translatie intro ENG 
- [x] Translatie intro FR
- [x] Translatie ontbinding NL 
- [x] Translatie ontbinding ENG
- [x] Translatie ontbinding FR 

### Overig
@alfamongrel Follow up? 
@TeppersBen Ben toevallig zin om te helpen. zodat je localization in laravel kunt aanleren? 

## Overige punten

- Na afsluiting van dit ticket moet er een deployment gebeuren op de server.

**Comment by Tjoosten** [comment]
**NOTE:** @TeppersBen Indien je wilt helpen zet ik een aparte branch op toegwijd aan deze issue

**Comment by Tjoosten** [comment]
branch `patch-16` is aangemaakt. Deze branch is toegeweid aan dit ticket. Gelieve dingen die niet relateerd zijn. Ere buiten te houden. 

Ook is er ineens een update gebeurd vanuit onze barebone.

**Comment by alfamongrel** [comment]
Al de vertalingen zijn in proces !
even geduld ik documenteer en archiveer ze 
Deadline : 28-06-2017

**Comment by Tjoosten** [comment]
Andere vertalingen moet een nieuw ticket worden opgemaakt per groep. Aangezien deze alleen gaat over de petitie tekst
